### ISSUE TITLE
Include autonomous system info

### ISSUE THREAD

**Issue by philrz** [brimdata/geoip-conn#39]
As requested by community user @omnidepp in https://github.com/brimdata/brim/issues/931#issuecomment-1127584110:

> Any chance this could be extended to use zeek's built-in mmdb_check_asn to also lookup the autonomous_system_organization for each IP address with the free Geoip2 ASN database?

**Comment by philrz** [comment]
I've got a working fork over at https://github.com/philrz/geoip-conn that includes the autonomous system number. I've not yet submitted a PR to the main repo https://github.com/brimdata/geoip-conn because it can't be included with a Brim release until the problem with the Zeek build system described in brimdata/zeek#61 is addressed. While waiting on that to be unblocked, users that are running custom Zeek installs or that are familiar with manually hacking Zeek scripts could use the https://github.com/philrz/geoip-conn fork to get ASN working in the meantime.

**Comment by omnidepp** [comment]
@philrz thank you for looking into this. Could you also include the actual autonomous_system_organization field from the ASN database and not just the as number? It is very useful in identifying malicious traffic or pinpointing the origin or destination of a connection.

**Comment by philrz** [comment]
@omnidepp: Understood. I looked closer at the Zeek built-in-functions (BIFs) that this package depends on to get the geolocation information from the MaxMind DB and unfortunately it looks like there's only currently a BIF to return the AS number, not the AS org info. I've filed an enhancement request with the Zeek team at zeek/zeek#2141 to see if there's any interest in adding it.

Out of curiosity, are you a "power user" that runs your own customized Zeek with Brim, or do you just use the one that ships with Brim? I ask because with the direction of the Brim projects, even if the Zeek team were to add the functionality to an upcoming release and this package were enhanced to take advantage of it, you may be waiting a while for it to make its way into a GA Brim release.

**Comment by omnidepp** [comment]
@philrz: Both, I sometimes deploy zeek with custom scripts and sometimes I just want to get a quick overview by dropping pcaps into the brim gui directly :)
